services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml
    networks:
      - api_gateway_network

networks:
  api_gateway_network:
    external: true
    name: api_gateway_network